version_variable: "app/_version.py:__version__"
upload_to_pypi: false
upload_to_github: true
changelog_file: "CHANGELOG.md"
branch: "main"
# Ejemplo de prerelease si tienes una rama 'next'
# prerelease_branches:
#   - name: "next"
#     prerelease: true
