name: 🚀 Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: write      # para poder push de tags y commits
      packages: write      # para publicar en GitHub Packages, si lo usas
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0         # trae todo el historial para leer commits
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.10'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Configure Poetry to use project venv
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run semantic-release publish
